dist: trusty
language: java
jdk:
- oraclejdk8
before_install:
- export TZ=Brazil/East
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    - secure: "RzGTR02KW5JFMzgM/o2MJj1DSO4oBEwPLVlJAcWnJWIiJ4rt0JY1fpIyfxTslMSJjv9hJIE+spkvDa3XPFrCQ7oyIVhhAi4L66isHgjcH0pp25MWbHQDeAfTZqPDffqQGhebqSj2Uof0It/QrmKW6g0r2RsNNmehWiM7rJ7odtdOc2ryKFTqnUlftvlv+NaweQB+GNjBGFjFhW0FkrVnTA/tWAZaukv8QRD9JxurXkgEn4pT1MeEbISkQ3JwI5yPQiVOAoeSIhY4NV/wLU2B3mE64coW+Rq+6jsyjCXCJvwPHVbaTOJw56g3NmaQxjlcawjRr1B3100UAtlFw8xNzrCRe4n6ZtNerQlmny7faQn96I/2Xv1Eb5uXikPfQh5R4prS3PqPCB3sOwntRYY+7rJT12p63+wDyHwUs657JX4/lcmHCaKjhq0WS7RwtnO5EPka8gJjLDn2l8HYWjwnvGU4UTXKWet9iYzZxFZ2YSnAVaNt7wOK0HT+pTyjCsMaOxeMnKhkcMegFgJ8kEkxE5LoCbuGsFzPfKcsUEUVH9mQnvHMzYykwAkVVcUD5eDOe+Z8mMj+PMMe1IbsT2yZchqurfGozX4GlWVZyhGzcy6Kk11GTOaR51peo9UCY9CacICBClzV/ygDAZQq8F3aheKV68a6T0SnN2hF3Ew4N70="
  app: $APP